#
# nanotodon for OpenBSD: Makefile
#

PROG = nanotodon
SRCS = config.c messages.c nanotodon.c
CFLAGS += -std=gnu99 -I/usr/local/include -DSUPPORT_XDG_BASE_DIR \
		-D_XOPEN_SOURCE_EXTENDED -Wno-format-security
LDFLAGS += -L${LOCALBASE}/lib -lcurses -lpthread -lcurl -ljson-c
BINDIR = ${LOCALBASE}/bin
NOMAN = 1

.include <bsd.prog.mk>
