# $OpenBSD$

COMMENT =	parse/write/merge/edit RSS/RDF/Atom syndication feeds

DISTNAME =	XML-FeedPP-0.95

CATEGORIES =	textproc

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan
RUN_DEPENDS =		textproc/p5-XML-TreePP>=0.39

PKG_ARCH =		*

.include <bsd.port.mk>
